### ISSUE TITLE
Pyzbar Issue

### ISSUE THREAD

**Issue by ilyesm** [hannob/vacdec#4]
Hi there!

When running the script I am getting the following errors:
`Traceback (most recent call last):
  File "vacdec.py", line 8, in <module>
    import pyzbar.pyzbar
  File "/usr/local/lib/python3.7/dist-packages/pyzbar/pyzbar.py", line 7, in <module>
    from .wrapper import (
  File "/usr/local/lib/python3.7/dist-packages/pyzbar/wrapper.py", line 143, in <module>
    c_uint_p,    # minor
  File "/usr/local/lib/python3.7/dist-packages/pyzbar/wrapper.py", line 136, in zbar_function
    return prototype((fname, load_libzbar()))
  File "/usr/local/lib/python3.7/dist-packages/pyzbar/wrapper.py", line 115, in load_libzbar
    libzbar, dependencies = zbar_library.load()
  File "/usr/local/lib/python3.7/dist-packages/pyzbar/zbar_library.py", line 65, in load
    raise ImportError('Unable to find zbar shared library')
ImportError: Unable to find zbar shared library`

Any ideas what could be happenning?

Thanks!

**Comment by stran0** [comment]
Use
python3 vacdec.py file
